version: '1'
services:
  database:
    container_name: postgresDB
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres@localhost
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  app:
    container_name: diplom
    image: 'diplom'
    build:
      context: .
    ports:
      - "8888:8888"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres